### ISSUE TITLE
您好，我的毕业设计和您的这篇论文类似，我想咨询您几个问题，请问怎么联系您，麻烦您看一下，有偿

### ISSUE THREAD

**Issue by airplane777** [virtualwiz/TensorRider_Movidius_NCS#1]
您好，我的毕业设计和您的这篇论文类似，我想咨询您几个问题，请问怎么联系您，麻烦您看一下，有偿

**Comment by virtualwiz** [comment]
如果有任何问题，请开issue吧，我会尽力回答

**Comment by airplane777** [comment]
我的毕业设计题目是  “基于神经网络控制的自动驾驶汽车轨迹选择优化算法”，我想知道是哪一种算法，还是用什么，本科学校不好，什么都不太懂，而且是电气自动化专业，分配老师分配到了偏信息专业，一头雾水，请老哥指点指点，或者您有详细代码一类我可以付钱

**Comment by airplane777** [comment]
我的毕业设计题目是 “基于神经网络控制的自动驾驶汽车轨迹选择优化算法”，我想知道是哪一种算法，还是用什么，本科学校不好，什么都不太懂，而且是电气自动化专业，分配老师分配到了偏信息专业，一头雾水，请老哥指点指点，或者您有详细代码一类我可以付钱



---原始邮件---
发件人: "Matthew (S Du)"<notifications@github.com&gt;
发送时间: 2021年1月5日(周二) 上午10:42
收件人: "virtualwiz/TensorRider_Self_Driving_Car"<TensorRider_Self_Driving_Car@noreply.github.com&gt;;
抄送: "airplane777"<2937766350@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [virtualwiz/TensorRider_Self_Driving_Car] 您好，我的毕业设计和您的这篇论文类似，我想咨询您几个问题，请问怎么联系您，麻烦您看一下，有偿 (#1)




 
如果有任何问题，请开issue吧，我会尽力回答

**Comment by virtualwiz** [comment]
已私信
